# Template for dataset descriptions
# Each dataset should have:
# - Name (key)
# - System role description containing:
#   - Dataset Description header
#   - Column descriptions with types and explanations
#   - Access instructions
#   - Special notes about data handling

template:
  dataset:
    name: str  # Will be used as the YAML key
    description:
      - role: system
        content: |
          [Dataset Description]:
          {description}

          {columns}

          You can access the entire dataset via the "data" variable.

          {special_notes}

column_format: |
  "{name}": {type}, {description}

special_notes_format: |
  {notes}

# Example structure:
# MyDataset:
#   - role: system
#     content: |
#       [Dataset Description]:
#       This dataset contains...
#
#       "column1": type, description
#       "column2": type, description
#
#       You can access the entire dataset via the "data" variable.
#
#       Additional notes about data handling...

# Output format validation schema
format:
  type: object
  properties:
    dataset_name:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          enum: [system]
        content:
          type: string
          pattern: |
            ^\[Dataset Description\]:
            .*
            .*".*":.*,.*
            .*
            You can access the entire dataset via the "data" variable\.
            .*$

# Example valid output:
# MyDataset:
#   - role: system
#     content: |
#       [Dataset Description]:
#       Dataset description here...
#
#       "Column1": type, description
#       "Column2": type, description
#
#       You can access the entire dataset via the "data" variable.
#
#       Additional notes... 